---
packages:
- name: riemann-tools
  version: 0dd2ee25ab4288b7c0938ea82e9bf529596004ef
  sha1: !binary |-
    OWUwNDFjYzY4N2FjYmQwNzk4YjFlOGQ5YjAzOTQ0YTdkOTJlZjc4MQ==
  fingerprint: !binary |-
    MGRkMmVlMjVhYjQyODhiN2MwOTM4ZWE4MmU5YmY1Mjk1OTYwMDRlZg==
  dependencies:
  - ruby
- name: riemann-mongodb
  version: fb444fdce5f7903f513ee1c4e22bd50fccea49dd
  sha1: !binary |-
    YmQ5N2JmNTQzOTkzN2Y1Njk1YTFlZTI2MWYzNjY2ZmUwY2E5NDI0MA==
  fingerprint: !binary |-
    ZmI0NDRmZGNlNWY3OTAzZjUxM2VlMWM0ZTIyYmQ1MGZjY2VhNDlkZA==
  dependencies:
  - ruby
- name: riemann-redis
  version: !binary |-
    MDMzOWRiOTljYTkzZTY0ZTkzNGYxMTZiMmUyMjczZDM0YzE2ZjNlYQ==
  sha1: !binary |-
    OTlmNjk5YmMzYzJlZWIzYWZkYjdkZjBjMWJkZTIwNmRiZjNiZjAzZQ==
  fingerprint: !binary |-
    MDMzOWRiOTljYTkzZTY0ZTkzNGYxMTZiMmUyMjczZDM0YzE2ZjNlYQ==
  dependencies:
  - ruby
- name: ruby
  version: cd4d8494a137e228e6358eb18eee7528e371a0a0
  sha1: !binary |-
    NjhjN2IzNTcxNGE4N2JmNjBmNmM4NzkyMDFkOTBlODYwOTE2MzdlOA==
  fingerprint: !binary |-
    Y2Q0ZDg0OTRhMTM3ZTIyOGU2MzU4ZWIxOGVlZTc1MjhlMzcxYTBhMA==
  dependencies: []
jobs:
- name: riemann-tools
  version: 6764427d98095af61830d76ca3068a026555a32d
  fingerprint: !binary |-
    Njc2NDQyN2Q5ODA5NWFmNjE4MzBkNzZjYTMwNjhhMDI2NTU1YTMyZA==
  sha1: !binary |-
    NWFmN2QzYjFlZDhkOTUxZGM1Y2Q1MDNhMGJjMGM0ZWVkZTliN2U3MA==
- name: riemann-mongodb
  version: !binary |-
    YzJiOGY5NWJkM2U4NWIyNGQzNTNmNGE0YWRlZjY1NzE2M2Y2MThlMA==
  fingerprint: !binary |-
    YzJiOGY5NWJkM2U4NWIyNGQzNTNmNGE0YWRlZjY1NzE2M2Y2MThlMA==
  sha1: !binary |-
    OTQ3NzMwOWQ2MDczNmNhZjY4Nzg3OWZlN2ZmYWY5M2RmNjA5ZDgwMA==
- name: riemann-zookeeper
  version: a2698be5bb568d4429652e9bf27464c946496f2b
  fingerprint: !binary |-
    YTI2OThiZTViYjU2OGQ0NDI5NjUyZTliZjI3NDY0Yzk0NjQ5NmYyYg==
  sha1: !binary |-
    ZWEwZjBhMTAyMzUwOWFiMzkyNjdiZGIxMjM5NGZmMmIzNzc0ZWY0OA==
- name: riemann-redis
  version: !binary |-
    YWMwMGZhNzlmMzMxYzY4ZjA5YzliYmUwMzk4NGYxMDI1ZTYwYmE5Ng==
  fingerprint: !binary |-
    YWMwMGZhNzlmMzMxYzY4ZjA5YzliYmUwMzk4NGYxMDI1ZTYwYmE5Ng==
  sha1: !binary |-
    NDliMDMxOTI4MzY3Mjg5ZDNiNDQwZWM1ZmEyN2IxY2IwOWEyYmNmNQ==
- name: riemann-elasticsearch
  version: 2f78b7a776dcf9f009005b8a371591e14b822c97
  fingerprint: !binary |-
    MmY3OGI3YTc3NmRjZjlmMDA5MDA1YjhhMzcxNTkxZTE0YjgyMmM5Nw==
  sha1: !binary |-
    MmU3Mzc3ZTIyYmE0NTU5Yzc3Nzk2YTAyYjllMGE2MzE0YjQwNmNlNg==
commit_hash: 111016ca
uncommitted_changes: true
name: riemann-tools-hybris
version: '6.3'
