meta:
  environment: riemanntools-warden

  stemcell:
    name: bosh-warden-boshlite-ubuntu
    version: latest

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000

jobs:
  - name: riemanntools
    networks:
      - name: riemanntools1

compilation:
  cloud_properties:
    name: random

resource_pools:
  - name: small_z1
    cloud_properties:
      name: random

networks:
- name: riemanntools1
  # Assumes up to 5 VMs, including 1 static and 4 dynamic.
  # Plus 5 (double the size) unused IPs, due to BOSH bug/quirk.
  subnets:
  - cloud_properties:
      name: random
    range: 10.244.32.0/30
    reserved:
    - 10.244.32.1
    static:
    - 10.244.32.2

  - cloud_properties:
      name: random
    range: 10.244.32.4/30
    reserved:
    - 10.244.32.5
    static: []
  - cloud_properties:
      name: random
    range: 10.244.32.8/30
    reserved:
    - 10.244.32.9
    static: []
  - cloud_properties:
      name: random
    range: 10.244.32.12/30
    reserved:
    - 10.244.32.13
    static: []
  - cloud_properties:
      name: random
    range: 10.244.32.16/30
    reserved:
    - 10.244.32.17
    static: []

  # Bonus double-sized network required due to BOSH oddity
  - cloud_properties:
      name: random
    range: 10.244.32.20/30
    reserved:
    - 10.244.32.21
    static: []
  - cloud_properties:
      name: random
    range: 10.244.32.24/30
    reserved:
    - 10.244.32.25
    static: []
  - cloud_properties:
      name: random
    range: 10.244.32.28/30
    reserved:
    - 10.244.32.29
    static: []
  - cloud_properties:
      name: random
    range: 10.244.32.32/30
    reserved:
    - 10.244.32.33
    static: []
  - cloud_properties:
      name: random
    range: 10.244.32.36/30
    reserved:
    - 10.244.32.37
    static: []
